GET http://localhost:3003/api/blogs

###

POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBhaW50ZXIiLCJpZCI6IjYwNmRjYjllYzQ0N2Q0NTE5OGY2YjlhZiIsImlhdCI6MTYxNzgwOTk0OH0.keqgKwP68tsAGGOmCHQYHSa-T4ancexCbv7SoCdu2lA

{
	"title": "TDD harms architecture",
		"author": "Robert C. Martin",
		"url": "http://blog.cleancoder.com/uncle-bob/2017/03/03/TDD-Harms-Architecture.html"
}

###

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Atomic Habits",
  "author": "James Clear",
  "url": "www.atomichabits.com",
  "likes": 0,
  "userId": "606ca4e7a30d3d0c6c8b3af9"
}

###

DELETE http://localhost:3003/api/blogs/606c271a0f1fa07960c45341

###

PUT http://localhost:3003/api/blogs/606c271a0f1fa07960c45341
Content-Type: application/json

{
  "title": "Atomic Habits",
  "author": "James Clear",
  "url": "www.atomichabits.com",
  "likes": 10
}