GET http://localhost:3003/api/blogs

###

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Atomic Habits",
  "author": "James Clear",
  "url": "www.atomichabits.com",
  "likes": 0
}

###

DELETE http://localhost:3003/api/blogs/606ebc4c2c563646945b8089

###

PUT http://localhost:3003/api/blogs/606c271a0f1fa07960c45341
Content-Type: application/json

{
  "title": "Atomic Habits",
  "author": "James Clear",
  "url": "www.atomichabits.com",
  "likes": 10
}