POST http://localhost:3003/api/users
Content-Type: application/json

{
  "name": "Bob Ross",
  "username" : "painter",
  "password": "bob123"
}

###

POST http://localhost:3003/api/users
Content-Type: application/json

{
  "name": "James Clear",
  "username": "jamec",
  "password": "atomicjames"
}

###

POST http://localhost:3003/api/users
Content-Type: application/json

{
  "name": "Charles Dickens",
  "username" : "charlie",
  "password": "xxxx",
  "blogs": "606c271a0f1fa07960c45341"
}

###

GET http://localhost:3003/api/users
